sudo: required

branches:
  only:
    - master

language: cpp
os: linux
compiler: gcc

install: make get-deps

before_install:
  - sudo apt-get update --fix-missing
  - sudo apt-get install build-essential m4 zlib1g-dev libbz2-dev libgmp3-dev automake

script:
  - autoreconf -if
  - ./configure
  - make
  - sudo make install
  - sudo make uninstall
